export const Categories: any = [
  "CORE IN MAJOR",
  "ELECTIVE IN MAJOR",
  "MINOR",
  "VOCATIONAL MINOR",
  "ABILITY ENHANCEMENT COURSE",
  "SKILL ENHANCEMENT COURSE",
  "VALUE ADDED COURSE",
  "MULTI-DISCIPLINARY COURSE",
];
