export const Courses: any[] = [
  //science
  {
    pathway: "Single Major",
    discipline: "Science",
    courses: [
      {
        semester: 1,
        DSC: "A(P),B(P),C(P)",
        AEC: "1(E)(With P)",
        SEC: "",
        MDC: "1",
        VAC: "1(OL)",
        total_courses: 6,
        total_credits: 21,
        total_hrs_week: 25,
      },
      {
        semester: 2,
        DSC: "A(P),B(P),C(P)",
        AEC: "1(OL)(With P)",
        SEC: "",
        MDC: "1",
        VAC: "1(E)",
        total_courses: 6,
        total_credits: 21,
        total_hrs_week: 25,
      },
      {
        semester: 3,
        DSC: "A,A,A(P),B(P)",
        AEC: "1(E)(With P)",
        SEC: "",
        MDC: "1(E&OL)(With KS)",
        VAC: "",
        total_courses: 6,
        total_credits: 21,
        total_hrs_week: 25,
      },
      {
        semester: 4,
        DSC: "A,A,A(P),C(P)",
        AEC: "1(OL)",
        SEC: "1(E)",
        MDC: "",
        VAC: "",
        total_courses: 6,
        total_credits: 22,
        total_hrs_week: 24,
      },
      {
        semester: 5,
        DSC: "A,A,A(P),A(P),A*",
        AEC: "",
        SEC: "1",
        MDC: "",
        VAC: "",
        total_courses: 6,
        total_credits: 23,
        total_hrs_week: 25,
      },
      {
        semester: 6,
        DSC: "A,A(P),A(P),A*",
        AEC: "",
        SEC: "1",
        MDC: "",
        VAC: "1(E)",
        total_courses: 6,
        total_credits: 22,
        total_hrs_week: 24,
      },
      {
        semester: "Total",
        DSC: "Major A:17 Minor(B+C):6",
        AEC: "4",
        SEC: "3",
        MDC: "3",
        VAC: "3",
        total_courses: 36,
        total_credits: "131+2(Internship)=133",
        total_hrs_week: 148,
      },
    ],
    courses_after_six_sem: [
      {
        semester: 7,
        DSC: "Major A, A ,A ,A ,A(P) ,A(P)",
        nature: "Six courses of first-year-PG level.",
        total_courses: 6,
        total_credits: 24,
        total_hrs_week: 26,
      },
      {
        semester: "8(1)",
        nature:
          "• Two courses of first-year-PG level • They should be taught in the blended mode. • The student can choose to do two online courses from repositories approved by the Board of Study. • Instead of two Major courses, the student can choose to do two Minor courses in any discipline. In this case, the two courses are of third-year-UG level (level 300 & above)  • Instead of Project, three courses of first-year PG level in the Major discipline can be chosen.  ",
        DSC: "Major A, A or Minor in any discipline B, B ",
        total_courses: 2,
        total_credits: 8,
        total_hrs_week: 8,
      },
      {
        semester: "8(2)",
        nature:
          " Instead of Project, three courses of first-year PG level in the Major discipline can be chosen.  ",
        DSC: "Project in A (credit 12) or Major A, A, A ",
        total_courses: 3,
        total_credits: 12,
        total_hrs_week: 12,
      },
      {
        semester: "Total of 7&8",
        DSC: "Major A:8 or 11 Project in A",
        nature: "",
        total_courses: "8 or 11",
        total_credits: 44,
        total_hrs_week: 46,
      },
      {
        semester: "Grand Total",
        DSC: "Major A:25 or 28 Minor(s):6 or 8",
        nature: "",
        total_courses: "44 or 47",
        total_credits: 177,
        total_hrs_week: 194,
      },
    ],
  },
  {
    pathway: " Major with multiple Disciplines ",
    discipline: "Science",
    courses: [
      {
        semester: 1,
        DSC: "A(P),B(P),C(P)",
        AEC: "1(E)(With P)",
        SEC: "",
        MDC: "1",
        VAC: "1(OL)",
        total_courses: 6,
        total_credits: 21,
        total_hrs_week: 25,
      },
      {
        semester: 2,
        DSC: "A(P),B(P),C(P)",
        AEC: "1(OL)(With P)",
        SEC: "",
        MDC: "1",
        VAC: "1(E)",
        total_courses: 6,
        total_credits: 21,
        total_hrs_week: 25,
      },
      {
        semester: 3,
        DSC: "A,A,A(P),B(P)",
        AEC: "1(E)(With P)",
        SEC: "",
        MDC: "1(E&OL)(With KS)",
        VAC: "",
        total_courses: 6,
        total_credits: 21,
        total_hrs_week: 25,
      },
      {
        semester: 4,
        DSC: "A,A,A(P),C(P)",
        AEC: "1(OL)",
        SEC: "1(E)",
        MDC: "",
        VAC: "",
        total_courses: 6,
        total_credits: 22,
        total_hrs_week: 24,
      },
      {
        semester: 5,
        DSC: "A,A,A(P),A(P),A*",
        AEC: "",
        SEC: "1",
        MDC: "",
        VAC: "",
        total_courses: 6,
        total_credits: 23,
        total_hrs_week: 25,
      },
      {
        semester: 6,
        DSC: "A,A(P),A(P),A*",
        AEC: "",
        SEC: "1",
        MDC: "",
        VAC: "1(E)",
        total_courses: 6,
        total_credits: 22,
        total_hrs_week: 24,
      },
      {
        semester: "Total",
        DSC: "Major A:17 Minor(B+C):6",
        AEC: "4",
        SEC: "3",
        MDC: "3",
        VAC: "3",
        total_courses: 36,
        total_credits: "131+2(Internship)=133",
        total_hrs_week: 148,
      },
    ],
    courses_after_six_sem: [
      {
        semester: 7,
        DSC: "Major A, A ,A ,A ,A(P) ,A(P)",
        nature: "Six courses of first-year-PG level.",
        total_courses: 6,
        total_credits: 24,
        total_hrs_week: 26,
      },
      {
        semester: "8(1)",
        nature:
          "• Two courses of first-year-PG level • They should be taught in the blended mode. • The student can choose to do two online courses from repositories approved by the Board of Study. • Instead of two Major courses, the student can choose to do two Minor courses in any discipline. In this case, the two courses are of third-year-UG level (level 300 & above)  • Instead of Project, three courses of first-year PG level in the Major discipline can be chosen.  ",
        DSC: "Major A, A or Minor in any discipline B, B ",
        total_credits: 8,
        total_hrs_week: 8,
      },
      {
        semester: "8(2)",
        nature:
          " Instead of Project, three courses of first-year PG level in the Major discipline can be chosen.  ",
        DSC: "Project in A (credit 12) or Major A, A, A ",
        total_courses: 3,
        total_credits: 12,
        total_hrs_week: 12,
      },
      {
        semester: "Total of 7&8",
        DSC: "Major A:8 or 11 Project in A",
        nature: "",
        total_courses: "8 or 11",
        total_credits: 44,
        total_hrs_week: 46,
      },
      {
        semester: "Grand Total",
        DSC: "Major A:25 or 28 Minor(s):6 or 8",
        nature: "",
        total_courses: "44 or 47",
        total_credits: 177,
        total_hrs_week: 194,
      },
    ],
  },
  {
    pathway: "Major with Minor",
    discipline: "Science",
    courses: [
      {
        semester: 1,
        DSC: "A(P),B(P),B(P)",
        AEC: "1(E)(With P)",
        SEC: "",
        MDC: "1",
        VAC: "1(OL)",
        total_courses: 6,
        total_credits: 21,
        total_hrs_week: 25,
      },
      {
        semester: 2,
        DSC: "A(P),B(P),B(P)",
        AEC: "1(OL)(With P)",
        SEC: "",
        MDC: "1",
        VAC: "1(E)",
        total_courses: 6,
        total_credits: 21,
        total_hrs_week: 25,
      },
      {
        semester: 3,
        DSC: "A,A,A(P),(P)",
        AEC: "1(E)(With P)",
        SEC: "",
        MDC: "1(E&OL)(With KS)",
        VAC: "",
        total_courses: 6,
        total_credits: 21,
        total_hrs_week: 25,
      },
      {
        semester: 4,
        DSC: "A,A,A(P),B(P)",
        AEC: "1(OL)",
        SEC: "1(E)",
        MDC: "",
        VAC: "",
        total_courses: 6,
        total_credits: 22,
        total_hrs_week: 24,
      },
      {
        semester: 5,
        DSC: "A,A,A(P),A(P),A*",
        AEC: "",
        SEC: "1",
        MDC: "",
        VAC: "",
        total_courses: 6,
        total_credits: 23,
        total_hrs_week: 25,
      },
      {
        semester: 6,
        DSC: "A,A(P),A(P),A*",
        AEC: "",
        SEC: "1",
        MDC: "",
        VAC: "1(E)",
        total_courses: 6,
        total_credits: 22,
        total_hrs_week: 24,
      },
      {
        semester: "Total",
        DSC: "Major A:17 Minor(B+C):6",
        AEC: "4",
        SEC: "3",
        MDC: "3",
        VAC: "3",
        total_courses: 36,
        total_credits: "131+2(Internship)=133",
        total_hrs_week: 148,
      },
    ],
    courses_after_six_sem: [
      {
        semester: 7,
        DSC: "Major A, A ,A ,A ,A(P) ,A(P)",
        nature: "Six courses of first-year-PG level.",
        total_courses: 6,
        total_credits: 24,
        total_hrs_week: 26,
      },
      {
        semester: "8(1)",
        nature:
          "• Two courses of first-year-PG level • They should be taught in the blended mode. • The student can choose to do two online courses from repositories approved by the Board of Study. • Instead of two Major courses, the student can choose to do two Minor courses in any discipline. In this case, the two courses are of third-year-UG level (level 300 & above)  • Instead of Project, three courses of first-year PG level in the Major discipline can be chosen.  ",
        DSC: "Major A, A or Minor in any discipline B, B ",
        total_courses: 2,
        total_credits: 8,
        total_hrs_week: 8,
      },
      {
        semester: "8(2)",
        nature:
          " Instead of Project, three courses of first-year PG level in the Major discipline can be chosen.  ",
        DSC: "Project in A (credit 12) or Major A, A, A ",
        total_courses: 3,
        total_credits: 12,
        total_hrs_week: 12,
      },
      {
        semester: "Total of 7&8",
        DSC: "Major A:8 or 11 Project in A",
        nature: "",
        total_courses: "8 or 11",
        total_credits: 44,
        total_hrs_week: 46,
      },
      {
        semester: "Grand Total",
        DSC: "Major A:25 or 28 Minor(s):6 or 8",
        nature: "",
        total_courses: "44 or 47",
        total_credits: 177,
        total_hrs_week: 194,
      },
    ],
  },

  {
    pathway: "Major with Vocational Minor",
    discipline: "Science",
    courses: [
      {
        semester: 1,
        DSC: "A(P),B(P),B(P)",
        AEC: "1(E)(With P)",
        SEC: "",
        MDC: "1",
        VAC: "1(OL)",
        total_courses: 6,
        total_credits: 21,
        total_hrs_week: 25,
      },
      {
        semester: 2,
        DSC: "A(P),B(P),B(P)",
        AEC: "1(OL)(With P)",
        SEC: "",
        MDC: "1",
        VAC: "1(E)",
        total_courses: 6,
        total_credits: 21,
        total_hrs_week: 25,
      },
      {
        semester: 3,
        DSC: "A,A,A(P),(P)",
        AEC: "1(E)(With P)",
        SEC: "",
        MDC: "1(E&OL)(With KS)",
        VAC: "",
        total_courses: 6,
        total_credits: 21,
        total_hrs_week: 25,
      },
      {
        semester: 4,
        DSC: "A,A,A(P),B(P)",
        AEC: "1(OL)",
        SEC: "1(E)",
        MDC: "",
        VAC: "",
        total_courses: 6,
        total_credits: 22,
        total_hrs_week: 24,
      },
      {
        semester: 5,
        DSC: "A,A,A(P),A(P),A*",
        AEC: "",
        SEC: "1",
        MDC: "",
        VAC: "",
        total_courses: 6,
        total_credits: 23,
        total_hrs_week: 25,
      },
      {
        semester: 6,
        DSC: "A,A(P),A(P),A*",
        AEC: "",
        SEC: "1",
        MDC: "",
        VAC: "1(E)",
        total_courses: 6,
        total_credits: 22,
        total_hrs_week: 24,
      },
      {
        semester: "Total",
        DSC: "Major A:17 Minor(B+C):6",
        AEC: "4",
        SEC: "3",
        MDC: "3",
        VAC: "3",
        total_courses: 36,
        total_credits: "131+2(Internship)=133",
        total_hrs_week: 148,
      },
    ],
    courses_after_six_sem: [
      {
        semester: 7,
        DSC: "Major A, A ,A ,A ,A(P) ,A(P)",
        nature: "Six courses of first-year-PG level.",
        total_courses: 6,
        total_credits: 24,
        total_hrs_week: 26,
      },
      {
        semester: "8(1)",
        nature:
          "• Two courses of first-year-PG level • They should be taught in the blended mode. • The student can choose to do two online courses from repositories approved by the Board of Study. • Instead of two Major courses, the student can choose to do two Minor courses in any discipline. In this case, the two courses are of third-year-UG level (level 300 & above)  • Instead of Project, three courses of first-year PG level in the Major discipline can be chosen.  ",
        DSC: "Major A, A or Minor in any discipline B, B ",
        total_courses: 2,
        total_credits: 8,
        total_hrs_week: 8,
      },
      {
        semester: "8(2)",
        nature:
          " Instead of Project, three courses of first-year PG level in the Major discipline can be chosen.  ",
        DSC: "Project in A (credit 12) or Major A, A, A ",
        total_courses: 3,
        total_credits: 12,
        total_hrs_week: 12,
      },
      {
        semester: "Total of 7&8",
        DSC: "Major A:8 or 11 Project in A",
        nature: "",
        total_courses: "8 or 11",
        total_credits: 44,
        total_hrs_week: 46,
      },
      {
        semester: "Grand Total",
        DSC: "Major A:25 or 28 Minor(s):6 or 8",
        nature: "",
        total_courses: "44 or 47",
        total_credits: 177,
        total_hrs_week: 194,
      },
    ],
  },

  {
    pathway: "Double Major",
    discipline: "Science",
    courses: [
      {
        semester: 1,
        DSC: "A1(P),A1(P),B2(P)",
        AEC: "1(E)(With P)",
        SEC: "",
        MDC: "A2",
        VAC: "A1",
        total_courses: 6,
        total_credits: 21,
        total_hrs_week: 25,
      },
      {
        semester: 2,
        DSC: "A1(P),A2(P),A2(P)",
        AEC: "1(OL)(With P)",
        SEC: "",
        MDC: "A1",
        VAC: "A1",
        total_courses: 6,
        total_credits: 21,
        total_hrs_week: 25,
      },
      {
        semester: 3,
        DSC: "A1,A1(P),A2,A2(P)",
        AEC: "1(E)(With P)",
        SEC: "",
        MDC: "A1",
        VAC: "",
        total_courses: 6,
        total_credits: 21,
        total_hrs_week: 25,
      },
      {
        semester: 4,
        DSC: "A1,A1(P),A2,A2(P)",
        AEC: "1(OL)",
        SEC: "A1",
        MDC: "",
        VAC: "",
        total_courses: 6,
        total_credits: 22,
        total_hrs_week: 24,
      },
      {
        semester: 5,
        DSC: "A1,A1(P),A1*,A2,A2(P)(*Elective A1)",
        AEC: "",
        SEC: "A2",
        MDC: "",
        VAC: "",
        total_courses: 6,
        total_credits: 23,
        total_hrs_week: 25,
      },
      {
        semester: 6,
        DSC: "A1,A1(P),A2(P),A2*(*Elective A2)",
        AEC: "",
        SEC: "A1",
        MDC: "",
        VAC: "A2",
        total_courses: 6,
        total_credits: 22,
        total_hrs_week: 24,
      },
      {
        semester: "Total",
        DSC: "Major A1:12 Major A2:11",
        AEC: "4",
        SEC: "3",
        MDC: "3",
        VAC: "3",
        total_courses: 36,
        total_credits: "131+2(Internship in A1)=133",
        total_hrs_week: 148,
      },
    ],
    courses_after_six_sem: [
      {
        semester: 7,
        DSC: "Major A1, A1 ,A1 ,A1 ,A1(P) ,A1(P)",
        nature: "Six courses of first-year-PG level.",
        total_courses: 6,
        total_credits: 24,
        total_hrs_week: 26,
      },
      {
        semester: "8(1)",
        nature:
          "• Two courses of first-year-PG level • They should be taught in the blended mode. • The student can choose to do two online courses from repositories approved by the Board of Study. • Instead of two Major courses, the student can choose to do two Minor courses in any discipline. In this case, the two courses are of third-year-UG level (level 300 & above)  • Instead of Project, three courses of first-year PG level in the Major discipline can be chosen.  ",
        DSC: "Major A, A or Minor in any discipline B, B ",
        total_courses: 2,
        total_credits: 8,
        total_hrs_week: 8,
      },
      {
        semester: "8(2)",
        nature:
          " Instead of Project, three courses of first-year PG level in the Major discipline can be chosen.  ",
        DSC: "Project in A (credit 12) or Major A, A, A ",
        total_courses: 3,
        total_credits: 12,
        total_hrs_week: 12,
      },
      {
        semester: "Total of 7&8",
        DSC: "Major A:8 or 11 Project in A",
        nature: "",
        total_courses: "8 or 11",
        total_credits: 44,
        total_hrs_week: 46,
      },
      {
        semester: "Grand Total",
        DSC: "Major A1:18 or 20 courses of 4-credits each + 6 courses of 3-credit each + internship of 2-credit = 92 or 100 credits",
        nature: "",
        total_courses: "44 or 47",
        total_credits: 177,
        total_hrs_week: 194,
      },
    ],
  },
  // Commerce
  {
    pathway: "Single Major",
    discipline: "Commerce",
    courses: [
      {
        semester: 1,
        DSC: "A,B(P),C(P)",
        AEC: "1(E)(With P)",
        SEC: "",
        MDC: "1",
        VAC: "1(OL)",
        total_courses: 6,
        total_credits: 21,
        total_hrs_week: 24,
      },
      {
        semester: 2,
        DSC: "A,B(P),C(P)",
        AEC: "1(OL)(With P)",
        SEC: "",
        MDC: "1",
        VAC: "1(E)",
        total_courses: 6,
        total_credits: 21,
        total_hrs_week: 24,
      },
      {
        semester: 3,
        DSC: "A,A,A(P),B",
        AEC: "1(E)(With P)",
        SEC: "",
        MDC: "1(E&OL)(With KS)",
        VAC: "",
        total_courses: 6,
        total_credits: 22,
        total_hrs_week: 24,
      },
      {
        semester: 4,
        DSC: "A,A,A(P),C",
        AEC: "1(OL)",
        SEC: "1(E)",
        MDC: "",
        VAC: "",
        total_courses: 6,
        total_credits: 22,
        total_hrs_week: 24,
      },
      {
        semester: 5,
        DSC: "A,A,A,A(P),A*(*Elective 1)",
        AEC: "",
        SEC: "1",
        MDC: "",
        VAC: "",
        total_courses: 6,
        total_credits: 23,
        total_hrs_week: 24,
      },
      {
        semester: 6,
        DSC: "A,A,A(P),A*(*Elective 2)",
        AEC: "",
        SEC: "1",
        MDC: "",
        VAC: "1(E)",
        total_courses: 6,
        total_credits: 22,
        total_hrs_week: 23,
      },
      {
        semester: "Total",
        DSC: "Major A:17 MinorB:3 MinorC:3",
        AEC: "4",
        SEC: "3",
        MDC: "3",
        VAC: "3",
        total_courses: 36,
        total_credits: "131+2(Internship)=133",
        total_hrs_week: 142,
      },
    ],
    courses_after_six_sem: [
      {
        semester: 7,
        DSC: "Major A, A ,A ,A ,A ,A",
        nature: "Six courses of first-year-PG level.",
        total_courses: 6,
        total_credits: 24,
        total_hrs_week: 24,
      },
      {
        semester: "8(1)",
        nature:
          "• Two courses of first-year-PG level • They should be taught in the blended mode. • The student can choose to do two online courses from repositories approved by the Board of Study. • Instead of two Major courses, the student can choose to do two Minor courses in any discipline. In this case, the two courses are of third-year-UG level (level 300 & above)  • Instead of Project, three courses of first-year PG level in the Major discipline can be chosen.  ",
        DSC: "Major A, A or Minor in any discipline B, B  /  Project in A (credit 12) or Major A, A, A ",
        total_courses: 2,
        total_credits: 8,
        total_hrs_week: 8,
      },
      {
        semester: "8(2)",
        nature:
          " Instead of Project, three courses of first-year PG level in the Major discipline can be chosen.  ",
        DSC: "Project in A (credit 12) or Major A, A, A ",
        total_courses: 3,
        total_credits: 12,
        total_hrs_week: 12,
      },
      {
        semester: "Total of 7&8",
        DSC: "Major A:8 or 11 Project in A",
        nature: "",
        total_courses: "8 or 11",
        total_credits: 44,
        total_hrs_week: 44,
      },
      {
        semester: "Grand Total",
        DSC: "Major A:25 or 28 Minor(s):6 or 8 Project in A",
        nature: "",
        total_courses: "44 or 47",
        total_credits: 177,
        total_hrs_week: 186,
      },
    ],
  },
  {
    pathway: " Major with multiple Disciplines ",
    discipline: "Commerce",
    courses: [
      {
        semester: 1,
        DSC: "A,B(P),C(P)",
        AEC: "1(E)(With P)",
        SEC: "",
        MDC: "1",
        VAC: "1(OL)",
        total_courses: 6,
        total_credits: 21,
        total_hrs_week: 24,
      },
      {
        semester: 2,
        DSC: "A,B(P),C(P)",
        AEC: "1(OL)(With P)",
        SEC: "",
        MDC: "1",
        VAC: "1(E)",
        total_courses: 6,
        total_credits: 21,
        total_hrs_week: 24,
      },
      {
        semester: 3,
        DSC: "A,A,A(P),B",
        AEC: "1(E)(With P)",
        SEC: "",
        MDC: "1(E&OL)(With KS)",
        VAC: "",
        total_courses: 6,
        total_credits: 2,
        total_hrs_week: 24,
      },
      {
        semester: 4,
        DSC: "A,A,A(P),C",
        AEC: "1(OL)",
        SEC: "1(E)",
        MDC: "",
        VAC: "",
        total_courses: 6,
        total_credits: 22,
        total_hrs_week: 23,
      },
      {
        semester: 5,
        DSC: "A,A,A,A(P),A*",
        AEC: "",
        SEC: "1",
        MDC: "",
        VAC: "",
        total_courses: 6,
        total_credits: 23,
        total_hrs_week: 24,
      },
      {
        semester: 6,
        DSC: "A,A,A(P),A*(*Elective 1)",
        AEC: "",
        SEC: "1",
        MDC: "",
        VAC: "1(E)",
        total_courses: 6,
        total_credits: 22,
        total_hrs_week: 23,
      },
      {
        semester: "Total",
        DSC: "Major A:17 MinorB:3 MajorC:3",
        AEC: "4",
        SEC: "3",
        MDC: "3",
        VAC: "3",
        total_courses: 36,
        total_credits: "131+2(Internship)=133",
        total_hrs_week: 142,
      },
    ],
    courses_after_six_sem: [
      {
        semester: 7,
        DSC: "Major A, A ,A ,A ,A ,A",
        nature: "Six courses of first-year-PG level.",
        total_courses: 6,
        total_credits: 24,
        total_hrs_week: 24,
      },
      {
        semester: "8(1)",
        nature:
          "• Two courses of first-year-PG level • They should be taught in the blended mode. • The student can choose to do two online courses from repositories approved by the Board of Study. • Instead of two Major courses, the student can choose to do two Minor courses in any discipline. In this case, the two courses are of third-year-UG level (level 300 & above)  • Instead of Project, three courses of first-year PG level in the Major discipline can be chosen.  ",
        DSC: "Major A, A or Minor in any discipline B, B  /  Project in A (credit 12) or Major A, A, A ",
        total_courses: 2,
        total_credits: 8,
        total_hrs_week: 8,
      },
      {
        semester: "8(2)",
        nature:
          " Instead of Project, three courses of first-year PG level in the Major discipline can be chosen.  ",
        DSC: "Project in A (credit 12) or Major A, A, A ",
        total_courses: 3,
        total_credits: 12,
        total_hrs_week: 12,
      },
      {
        semester: "Total of 7&8",
        DSC: "Major A:8 or 11 Project in A",
        nature: "",
        total_courses: "8 or 11",
        total_credits: 44,
        total_hrs_week: 44,
      },
      {
        semester: "Grand Total",
        DSC: "Major A:25 or 28 Minor(s):6 or 8 Project in A",
        nature: "",
        total_courses: "44 or 47",
        total_credits: 177,
        total_hrs_week: 186,
      },
    ],
  },
  {
    pathway: "Major with Minor",
    discipline: "Commerce",
    courses: [
      {
        semester: 1,
        DSC: "A,B(P),B(P)",
        AEC: "1(E)(With P)",
        SEC: "",
        MDC: "1",
        VAC: "1(OL)",
        total_courses: 6,
        total_credits: 21,
        total_hrs_week: 24,
      },
      {
        semester: 2,
        DSC: "A,B(P),B(P)",
        AEC: "1(OL)(With P)",
        SEC: "",
        MDC: "1",
        VAC: "1(E)",
        total_courses: 6,
        total_credits: 21,
        total_hrs_week: 24,
      },
      {
        semester: 3,
        DSC: "A,A,A(P),B",
        AEC: "1(E)(With P)",
        SEC: "",
        MDC: "1(E&OL)(With KS)",
        VAC: "",
        total_courses: 6,
        total_credits: 22,
        total_hrs_week: 24,
      },
      {
        semester: 4,
        DSC: "A,A,A(P),B",
        AEC: "1(OL)",
        SEC: "1(E)",
        MDC: "",
        VAC: "",
        total_courses: 6,
        total_credits: 22,
        total_hrs_week: 23,
      },
      {
        semester: 5,
        DSC: "A,A,A,A(P),A*(*Elective 1)",
        AEC: "",
        SEC: "1",
        MDC: "",
        VAC: "",
        total_courses: 6,
        total_credits: 23,
        total_hrs_week: 24,
      },
      {
        semester: 6,
        DSC: "A,A,A(P),A*(*Elective 2)",
        AEC: "",
        SEC: "1",
        MDC: "",
        VAC: "1(E)",
        total_courses: 6,
        total_credits: 22,
        total_hrs_week: 23,
      },
      {
        semester: "Total",
        DSC: "Major A:17 MinorB:6",
        AEC: "4",
        SEC: "3",
        MDC: "3",
        VAC: "3",
        total_courses: 36,
        total_credits: "131+2(Internship)=133",
        total_hrs_week: 142,
      },
    ],
    courses_after_six_sem: [
      {
        semester: 7,
        DSC: "Major A, A ,A ,A ,A ,A",
        nature: "Six courses of first-year-PG level.",
        total_courses: 6,
        total_credits: 24,
        total_hrs_week: 26,
      },
      {
        semester: "8(1)",
        nature:
          "• Two courses of first-year-PG level • They should be taught in the blended mode. • The student can choose to do two online courses from repositories approved by the Board of Study. • Instead of two Major courses, the student can choose to do two Minor courses in any discipline. In this case, the two courses are of third-year-UG level (level 300 & above)  • Instead of Project, three courses of first-year PG level in the Major discipline can be chosen.  ",
        DSC: "Major A, A or Minor in any discipline B, B  /  Project in A (credit 12) or Major A, A, A ",
        total_courses: 2,
        total_credits: 8,
        total_hrs_week: 8,
      },
      {
        semester: "8(2)",
        nature:
          " Instead of Project, three courses of first-year PG level in the Major discipline can be chosen.  ",
        DSC: "Project in A (credit 12) or Major A, A, A ",
        total_courses: 3,
        total_credits: 12,
        total_hrs_week: 12,
      },
      {
        semester: "Total of 7&8",
        DSC: "Major A:8 or 11 Project in A",
        nature: "",
        total_courses: "8 or 11",
        total_credits: 44,
        total_hrs_week: 44,
      },
      {
        semester: "Grand Total",
        DSC: "Major A:25 or 28 Minor(s):6 or 8 Project in A",
        nature: "",
        total_courses: "44 or 47",
        total_credits: 177,
        total_hrs_week: 186,
      },
    ],
  },

  {
    pathway: "Major with Vocational Minor",
    discipline: "Commerce",
    courses: [
      {
        semester: 1,
        DSC: "A,B(P),B(P)",
        AEC: "1(E)(With P)",
        SEC: "",
        MDC: "1",
        VAC: "1(OL)",
        total_courses: 6,
        total_credits: 21,
        total_hrs_week: 24,
      },
      {
        semester: 2,
        DSC: "A,B(P),B(P)",
        AEC: "1(OL)(With P)",
        SEC: "",
        MDC: "1",
        VAC: "1(E)",
        total_courses: 6,
        total_credits: 21,
        total_hrs_week: 24,
      },
      {
        semester: 3,
        DSC: "A,A,A(P),B",
        AEC: "1(E)(With P)",
        SEC: "",
        MDC: "1(E&OL)(With KS)",
        VAC: "",
        total_courses: 6,
        total_credits: 22,
        total_hrs_week: 24,
      },
      {
        semester: 4,
        DSC: "A,A,A(P),B",
        AEC: "1(OL)",
        SEC: "1(E)",
        MDC: "",
        VAC: "",
        total_courses: 6,
        total_credits: 22,
        total_hrs_week: 23,
      },
      {
        semester: 5,
        DSC: "A,A,A,A(P),A*(*Elective 1)",
        AEC: "",
        SEC: "1",
        MDC: "",
        VAC: "",
        total_courses: 6,
        total_credits: 23,
        total_hrs_week: 24,
      },
      {
        semester: 6,
        DSC: "A,A,A(P),A*(*Elective 2)",
        AEC: "",
        SEC: "1",
        MDC: "",
        VAC: "1(E)",
        total_courses: 6,
        total_credits: 22,
        total_hrs_week: 23,
      },
      {
        semester: "Total",
        DSC: "Major A:17 MinorB:6",
        AEC: "4",
        SEC: "3",
        MDC: "3",
        VAC: "3",
        total_courses: 36,
        total_credits: "131+2(Internship)=133",
        total_hrs_week: 142,
      },
    ],
    courses_after_six_sem: [
      {
        semester: 7,
        DSC: "Major A, A ,A ,A ,A ,A",
        nature: "Six courses of first-year-PG level.",
        total_courses: 6,
        total_credits: 24,
        total_hrs_week: 24,
      },
      {
        semester: "8(1)",
        nature:
          "• Two courses of first-year-PG level • They should be taught in the blended mode. • The student can choose to do two online courses from repositories approved by the Board of Study. • Instead of two Major courses, the student can choose to do two Minor courses in any discipline. In this case, the two courses are of third-year-UG level (level 300 & above)  • Instead of Project, three courses of first-year PG level in the Major discipline can be chosen.  ",
        DSC: "Major A, A or Minor in any discipline B, B  /  Project in A (credit 12) or Major A, A, A ",
        total_courses: 2,
        total_credits: 8,
        total_hrs_week: 8,
      },
      {
        semester: "8(2)",
        nature:
          " Instead of Project, three courses of first-year PG level in the Major discipline can be chosen.  ",
        DSC: "Project in A (credit 12) or Major A, A, A ",
        total_courses: 3,
        total_credits: 12,
        total_hrs_week: 12,
      },
      {
        semester: "Total of 7&8",
        DSC: "Major A:8 or 11 Project in A",
        nature: "",
        total_courses: "8 or 11",
        total_credits: 44,
        total_hrs_week: 44,
      },
      {
        semester: "Grand Total",
        DSC: "Major A:25 or 28 Minor(s):6 or 8 Project in A",
        nature: "",
        total_courses: "44 or 47",
        total_credits: 177,
        total_hrs_week: 186,
      },
    ],
  },

  {
    pathway: "Double Major",
    discipline: "Commerce",
    courses: [
      {
        semester: 1,
        DSC: "A1,A1(P),A2(P)",
        AEC: "1(E)(With P)",
        SEC: "",
        MDC: "A2",
        VAC: "A1",
        total_courses: 6,
        total_credits: 21,
        total_hrs_week: 24,
      },
      {
        semester: 2,
        DSC: "A1(P),A2,A2(P)",
        AEC: "1(OL)(With P)",
        SEC: "",
        MDC: "A1",
        VAC: "A1",
        total_courses: 6,
        total_credits: 21,
        total_hrs_week: 24,
      },
      {
        semester: 3,
        DSC: "A1,A1(P),A2,A2",
        AEC: "1(E)(With P)",
        SEC: "",
        MDC: "A1",
        VAC: "",
        total_courses: 6,
        total_credits: 22,
        total_hrs_week: 24,
      },
      {
        semester: 4,
        DSC: "A1,A1,A2,A2(P)",
        AEC: "1(OL)",
        SEC: "A1",
        MDC: "",
        VAC: "",
        total_courses: 6,
        total_credits: 22,
        total_hrs_week: 23,
      },
      {
        semester: 5,
        DSC: "A1,A1,A1*,A2,A2(P)(*Elective A1)",
        AEC: "",
        SEC: "A2",
        MDC: "",
        VAC: "",
        total_courses: 6,
        total_credits: 23,
        total_hrs_week: 23,
      },
      {
        semester: 6,
        DSC: "A1,A1(P),A2,A2*(*Elective A2)",
        AEC: "",
        SEC: "A1",
        MDC: "",
        VAC: "A2",
        total_courses: 6,
        total_credits: 22,
        total_hrs_week: 23,
      },
      {
        semester: "Total",
        DSC: "Major A1:12 Major A2:11",
        AEC: "4",
        SEC: "3",
        MDC: "3",
        VAC: "3",
        total_courses: 36,
        total_credits: "131+2(Internship in A1)=133",
        total_hrs_week: 142,
      },
    ],
    courses_after_six_sem: [
      {
        semester: 7,
        DSC: "Major A1, A1 ,A1 ,A1 ,A1 ,A1",
        nature: "Six courses of first-year-PG level.",
        total_courses: 6,
        total_credits: 24,
        total_hrs_week: 24,
      },
      {
        semester: "8(1)",
        nature:
          "• Two courses of first-year-PG level • They should be taught in the blended mode. • The student can choose to do two online courses from repositories approved by the Board of Study. • Instead of two Major courses, the student can choose to do two Minor courses in any discipline. In this case, the two courses are of third-year-UG level (level 300 & above)  • Instead of Project, three courses of first-year PG level in the Major discipline can be chosen.  ",
        DSC: "Major A, A or Minor in any discipline B, B",
        total_courses: 2,
        total_credits: 8,
        total_hrs_week: 8,
      },
      {
        semester: "8(2)",
        nature:
          " Instead of Project, three courses of first-year PG level in the Major discipline can be chosen.  ",
        DSC: "Project in A (credit 12) or Major A, A, A ",
        total_courses: 3,
        total_credits: 12,
        total_hrs_week: 12,
      },
      {
        semester: "Total of 7&8",
        DSC: "Major A:8 or 11 Project in A1",
        nature: "",
        total_courses: "8 or 11",
        total_credits: 44,
        total_hrs_week: 44,
      },
      {
        semester: "Grand Total",
        DSC: "Major A1:18 or 20 courses of 4-credits each + 6 courses of 3-credit each + internship of 2-credit = 92 or 100 credits",
        nature: "",
        total_courses: "44 or 47",
        total_credits: 177,
        total_hrs_week: 186,
      },
    ],
  },

  // Management

  {
    pathway: "Single Major",
    discipline: "Management",
    courses: [
      {
        semester: 1,
        DSC: "A,B(P),C(P)",
        AEC: "1(E)(With P)",
        SEC: "",
        MDC: "1",
        VAC: "1(OL)",
        total_courses: 6,
        total_credits: 21,
        total_hrs_week: 24,
      },
      {
        semester: 2,
        DSC: "A,B(P),C(P)",
        AEC: "1(OL)(With P)",
        SEC: "",
        MDC: "1",
        VAC: "1(E)",
        total_courses: 6,
        total_credits: 21,
        total_hrs_week: 24,
      },
      {
        semester: 3,
        DSC: "A,A,A(P),B",
        AEC: "1(E)(With P)",
        SEC: "",
        MDC: "1(E&OL)(With KS)",
        VAC: "",
        total_courses: 6,
        total_credits: 22,
        total_hrs_week: 24,
      },
      {
        semester: 4,
        DSC: "A,A,A(P),C",
        AEC: "1(OL)",
        SEC: "1(E)",
        MDC: "",
        VAC: "",
        total_courses: 6,
        total_credits: 22,
        total_hrs_week: 24,
      },
      {
        semester: 5,
        DSC: "A,A,A,A(P),A*(*Elective 1)",
        AEC: "",
        SEC: "1",
        MDC: "",
        VAC: "",
        total_courses: 6,
        total_credits: 23,
        total_hrs_week: 24,
      },
      {
        semester: 6,
        DSC: "A,A,A(P),A*(*Elective 2)",
        AEC: "",
        SEC: "1",
        MDC: "",
        VAC: "1(E)",
        total_courses: 6,
        total_credits: 22,
        total_hrs_week: 23,
      },
      {
        semester: "Total",
        DSC: "Major A:17 MinorB:3 MinorC:3",
        AEC: "4",
        SEC: "3",
        MDC: "3",
        VAC: "3",
        total_courses: 36,
        total_credits: "131+2(Internship)=133",
        total_hrs_week: 142,
      },
    ],
    courses_after_six_sem: [
      {
        semester: 7,
        DSC: "Major A, A ,A ,A ,A ,A",
        nature: "Six courses of first-year-PG level.",
        total_courses: 6,
        total_credits: 24,
        total_hrs_week: 24,
      },
      {
        semester: "8(1)",
        nature:
          "• Two courses of first-year-PG level • They should be taught in the blended mode. • The student can choose to do two online courses from repositories approved by the Board of Study. • Instead of two Major courses, the student can choose to do two Minor courses in any discipline. In this case, the two courses are of third-year-UG level (level 300 & above)  • Instead of Project, three courses of first-year PG level in the Major discipline can be chosen.  ",
        DSC: "Major A, A or Minor in any discipline B, B  /  Project in A (credit 12) or Major A, A, A ",
        total_courses: 2,
        total_credits: 8,
        total_hrs_week: 8,
      },
      {
        semester: "8(2)",
        nature:
          " Instead of Project, three courses of first-year PG level in the Major discipline can be chosen.  ",
        DSC: "Project in A (credit 12) or Major A, A, A ",
        total_courses: 3,
        total_credits: 12,
        total_hrs_week: 12,
      },
      {
        semester: "Total of 7&8",
        DSC: "Major A:8 or 11 Project in A",
        nature: "",
        total_courses: "8 or 11",
        total_credits: 44,
        total_hrs_week: 44,
      },
      {
        semester: "Grand Total",
        DSC: "Major A:25 or 28 Minor(s):6 or 8 Project in A",
        nature: "",
        total_courses: "44 or 47",
        total_credits: 177,
        total_hrs_week: 186,
      },
    ],
  },
  {
    pathway: " Major with multiple Disciplines ",
    discipline: "Management",
    courses: [
      {
        semester: 1,
        DSC: "A,B(P),C(P)",
        AEC: "1(E)(With P)",
        SEC: "",
        MDC: "1",
        VAC: "1(OL)",
        total_courses: 6,
        total_credits: 21,
        total_hrs_week: 24,
      },
      {
        semester: 2,
        DSC: "A,B(P),C(P)",
        AEC: "1(OL)(With P)",
        SEC: "",
        MDC: "1",
        VAC: "1(E)",
        total_courses: 6,
        total_credits: 21,
        total_hrs_week: 24,
      },
      {
        semester: 3,
        DSC: "A,A,A(P),B",
        AEC: "1(E)(With P)",
        SEC: "",
        MDC: "1(E&OL)(With KS)",
        VAC: "",
        total_courses: 6,
        total_credits: 2,
        total_hrs_week: 24,
      },
      {
        semester: 4,
        DSC: "A,A,A(P),C",
        AEC: "1(OL)",
        SEC: "1(E)",
        MDC: "",
        VAC: "",
        total_courses: 6,
        total_credits: 22,
        total_hrs_week: 23,
      },
      {
        semester: 5,
        DSC: "A,A,A,A(P),A*",
        AEC: "",
        SEC: "1",
        MDC: "",
        VAC: "",
        total_courses: 6,
        total_credits: 23,
        total_hrs_week: 24,
      },
      {
        semester: 6,
        DSC: "A,A,A(P),A*(*Elective 1)",
        AEC: "",
        SEC: "1",
        MDC: "",
        VAC: "1(E)",
        total_courses: 6,
        total_credits: 22,
        total_hrs_week: 23,
      },
      {
        semester: "Total",
        DSC: "Major A:17 MinorB:3 MajorC:3",
        AEC: "4",
        SEC: "3",
        MDC: "3",
        VAC: "3",
        total_courses: 36,
        total_credits: "131+2(Internship)=133",
        total_hrs_week: 142,
      },
    ],
    courses_after_six_sem: [
      {
        semester: 7,
        DSC: "Major A, A ,A ,A ,A ,A",
        nature: "Six courses of first-year-PG level.",
        total_courses: 6,
        total_credits: 24,
        total_hrs_week: 24,
      },
      {
        semester: "8(1)",
        nature:
          "• Two courses of first-year-PG level • They should be taught in the blended mode. • The student can choose to do two online courses from repositories approved by the Board of Study. • Instead of two Major courses, the student can choose to do two Minor courses in any discipline. In this case, the two courses are of third-year-UG level (level 300 & above)  • Instead of Project, three courses of first-year PG level in the Major discipline can be chosen.  ",
        DSC: "Major A, A or Minor in any discipline B, B  /  Project in A (credit 12) or Major A, A, A ",
        total_courses: 2,
        total_credits: 8,
        total_hrs_week: 8,
      },
      {
        semester: "8(2)",
        nature:
          " Instead of Project, three courses of first-year PG level in the Major discipline can be chosen.  ",
        DSC: "Project in A (credit 12) or Major A, A, A ",
        total_courses: 3,
        total_credits: 12,
        total_hrs_week: 12,
      },
      {
        semester: "Total of 7&8",
        DSC: "Major A:8 or 11 Project in A",
        nature: "",
        total_courses: "8 or 11",
        total_credits: 44,
        total_hrs_week: 44,
      },
      {
        semester: "Grand Total",
        DSC: "Major A:25 or 28 Minor(s):6 or 8 Project in A",
        nature: "",
        total_courses: "44 or 47",
        total_credits: 177,
        total_hrs_week: 186,
      },
    ],
  },
  {
    pathway: "Major with Minor",
    discipline: "Management",
    courses: [
      {
        semester: 1,
        DSC: "A,B(P),B(P)",
        AEC: "1(E)(With P)",
        SEC: "",
        MDC: "1",
        VAC: "1(OL)",
        total_courses: 6,
        total_credits: 21,
        total_hrs_week: 24,
      },
      {
        semester: 2,
        DSC: "A,B(P),B(P)",
        AEC: "1(OL)(With P)",
        SEC: "",
        MDC: "1",
        VAC: "1(E)",
        total_courses: 6,
        total_credits: 21,
        total_hrs_week: 24,
      },
      {
        semester: 3,
        DSC: "A,A,A(P),B",
        AEC: "1(E)(With P)",
        SEC: "",
        MDC: "1(E&OL)(With KS)",
        VAC: "",
        total_courses: 6,
        total_credits: 22,
        total_hrs_week: 24,
      },
      {
        semester: 4,
        DSC: "A,A,A(P),B",
        AEC: "1(OL)",
        SEC: "1(E)",
        MDC: "",
        VAC: "",
        total_courses: 6,
        total_credits: 22,
        total_hrs_week: 23,
      },
      {
        semester: 5,
        DSC: "A,A,A,A(P),A*(*Elective 1)",
        AEC: "",
        SEC: "1",
        MDC: "",
        VAC: "",
        total_courses: 6,
        total_credits: 23,
        total_hrs_week: 24,
      },
      {
        semester: 6,
        DSC: "A,A,A(P),A*(*Elective 2)",
        AEC: "",
        SEC: "1",
        MDC: "",
        VAC: "1(E)",
        total_courses: 6,
        total_credits: 22,
        total_hrs_week: 23,
      },
      {
        semester: "Total",
        DSC: "Major A:17 MinorB:6",
        AEC: "4",
        SEC: "3",
        MDC: "3",
        VAC: "3",
        total_courses: 36,
        total_credits: "131+2(Internship)=133",
        total_hrs_week: 142,
      },
    ],
    courses_after_six_sem: [
      {
        semester: 7,
        DSC: "Major A, A ,A ,A ,A ,A",
        nature: "Six courses of first-year-PG level.",
        total_courses: 6,
        total_credits: 24,
        total_hrs_week: 26,
      },
      {
        semester: "8(1)",
        nature:
          "• Two courses of first-year-PG level • They should be taught in the blended mode. • The student can choose to do two online courses from repositories approved by the Board of Study. • Instead of two Major courses, the student can choose to do two Minor courses in any discipline. In this case, the two courses are of third-year-UG level (level 300 & above)  • Instead of Project, three courses of first-year PG level in the Major discipline can be chosen.  ",
        DSC: "Major A, A or Minor in any discipline B, B  /  Project in A (credit 12) or Major A, A, A ",
        total_courses: 2,
        total_credits: 8,
        total_hrs_week: 8,
      },
      {
        semester: "8(2)",
        nature:
          " Instead of Project, three courses of first-year PG level in the Major discipline can be chosen.  ",
        DSC: "Project in A (credit 12) or Major A, A, A ",
        total_courses: 3,
        total_credits: 12,
        total_hrs_week: 12,
      },
      {
        semester: "Total of 7&8",
        DSC: "Major A:8 or 11 Project in A",
        nature: "",
        total_courses: "8 or 11",
        total_credits: 44,
        total_hrs_week: 44,
      },
      {
        semester: "Grand Total",
        DSC: "Major A:25 or 28 Minor(s):6 or 8 Project in A",
        nature: "",
        total_courses: "44 or 47",
        total_credits: 177,
        total_hrs_week: 186,
      },
    ],
  },

  {
    pathway: "Major with Vocational Minor",
    discipline: "Management",
    courses: [
      {
        semester: 1,
        DSC: "A,B(P),B(P)",
        AEC: "1(E)(With P)",
        SEC: "",
        MDC: "1",
        VAC: "1(OL)",
        total_courses: 6,
        total_credits: 21,
        total_hrs_week: 24,
      },
      {
        semester: 2,
        DSC: "A,B(P),B(P)",
        AEC: "1(OL)(With P)",
        SEC: "",
        MDC: "1",
        VAC: "1(E)",
        total_courses: 6,
        total_credits: 21,
        total_hrs_week: 24,
      },
      {
        semester: 3,
        DSC: "A,A,A(P),B",
        AEC: "1(E)(With P)",
        SEC: "",
        MDC: "1(E&OL)(With KS)",
        VAC: "",
        total_courses: 6,
        total_credits: 22,
        total_hrs_week: 24,
      },
      {
        semester: 4,
        DSC: "A,A,A(P),B",
        AEC: "1(OL)",
        SEC: "1(E)",
        MDC: "",
        VAC: "",
        total_courses: 6,
        total_credits: 22,
        total_hrs_week: 23,
      },
      {
        semester: 5,
        DSC: "A,A,A,A(P),A*(*Elective 1)",
        AEC: "",
        SEC: "1",
        MDC: "",
        VAC: "",
        total_courses: 6,
        total_credits: 23,
        total_hrs_week: 24,
      },
      {
        semester: 6,
        DSC: "A,A,A(P),A*(*Elective 2)",
        AEC: "",
        SEC: "1",
        MDC: "",
        VAC: "1(E)",
        total_courses: 6,
        total_credits: 22,
        total_hrs_week: 23,
      },
      {
        semester: "Total",
        DSC: "Major A:17 MinorB:6",
        AEC: "4",
        SEC: "3",
        MDC: "3",
        VAC: "3",
        total_courses: 36,
        total_credits: "131+2(Internship)=133",
        total_hrs_week: 142,
      },
    ],
    courses_after_six_sem: [
      {
        semester: 7,
        DSC: "Major A, A ,A ,A ,A ,A",
        nature: "Six courses of first-year-PG level.",
        total_courses: 6,
        total_credits: 24,
        total_hrs_week: 24,
      },
      {
        semester: "8(1)",
        nature:
          "• Two courses of first-year-PG level • They should be taught in the blended mode. • The student can choose to do two online courses from repositories approved by the Board of Study. • Instead of two Major courses, the student can choose to do two Minor courses in any discipline. In this case, the two courses are of third-year-UG level (level 300 & above)  • Instead of Project, three courses of first-year PG level in the Major discipline can be chosen.  ",
        DSC: "Major A, A or Minor in any discipline B, B  /  Project in A (credit 12) or Major A, A, A ",
        total_courses: 2,
        total_credits: 8,
        total_hrs_week: 8,
      },
      {
        semester: "8(2)",
        nature:
          " Instead of Project, three courses of first-year PG level in the Major discipline can be chosen.  ",
        DSC: "Project in A (credit 12) or Major A, A, A ",
        total_courses: 3,
        total_credits: 12,
        total_hrs_week: 12,
      },
      {
        semester: "Total of 7&8",
        DSC: "Major A:8 or 11 Project in A",
        nature: "",
        total_courses: "8 or 11",
        total_credits: 44,
        total_hrs_week: 44,
      },
      {
        semester: "Grand Total",
        DSC: "Major A:25 or 28 Minor(s):6 or 8 Project in A",
        nature: "",
        total_courses: "44 or 47",
        total_credits: 177,
        total_hrs_week: 186,
      },
    ],
  },

  {
    pathway: "Double Major",
    discipline: "Management",
    courses: [
      {
        semester: 1,
        DSC: "A1,A1(P),A2(P)",
        AEC: "1(E)(With P)",
        SEC: "",
        MDC: "A2",
        VAC: "A1",
        total_courses: 6,
        total_credits: 21,
        total_hrs_week: 24,
      },
      {
        semester: 2,
        DSC: "A1(P),A2,A2(P)",
        AEC: "1(OL)(With P)",
        SEC: "",
        MDC: "A1",
        VAC: "A1",
        total_courses: 6,
        total_credits: 21,
        total_hrs_week: 24,
      },
      {
        semester: 3,
        DSC: "A1,A1(P),A2,A2",
        AEC: "1(E)(With P)",
        SEC: "",
        MDC: "A1",
        VAC: "",
        total_courses: 6,
        total_credits: 22,
        total_hrs_week: 24,
      },
      {
        semester: 4,
        DSC: "A1,A1,A2,A2(P)",
        AEC: "1(OL)",
        SEC: "A1",
        MDC: "",
        VAC: "",
        total_courses: 6,
        total_credits: 22,
        total_hrs_week: 23,
      },
      {
        semester: 5,
        DSC: "A1,A1,A1*,A2,A2(P)(*Elective A1)",
        AEC: "",
        SEC: "A2",
        MDC: "",
        VAC: "",
        total_courses: 6,
        total_credits: 23,
        total_hrs_week: 23,
      },
      {
        semester: 6,
        DSC: "A1,A1(P),A2,A2*(*Elective A2)",
        AEC: "",
        SEC: "A1",
        MDC: "",
        VAC: "A2",
        total_courses: 6,
        total_credits: 22,
        total_hrs_week: 23,
      },
      {
        semester: "Total",
        DSC: "Major A1:12 Major A2:11",
        AEC: "4",
        SEC: "3",
        MDC: "3",
        VAC: "3",
        total_courses: 36,
        total_credits: "131+2(Internship in A1)=133",
        total_hrs_week: 142,
      },
    ],
    courses_after_six_sem: [
      {
        semester: 7,
        DSC: "Major A1, A1 ,A1 ,A1 ,A1 ,A1",
        nature: "Six courses of first-year-PG level.",
        total_courses: 6,
        total_credits: 24,
        total_hrs_week: 24,
      },
      {
        semester: "8(1)",
        nature:
          "• Two courses of first-year-PG level • They should be taught in the blended mode. • The student can choose to do two online courses from repositories approved by the Board of Study. • Instead of two Major courses, the student can choose to do two Minor courses in any discipline. In this case, the two courses are of third-year-UG level (level 300 & above)  • Instead of Project, three courses of first-year PG level in the Major discipline can be chosen.  ",
        DSC: "Major A, A or Minor in any discipline B, B",
        total_courses: 2,
        total_credits: 8,
        total_hrs_week: 8,
      },
      {
        semester: "8(2)",
        nature:
          " Instead of Project, three courses of first-year PG level in the Major discipline can be chosen.  ",
        DSC: "Project in A (credit 12) or Major A, A, A ",
        total_courses: 3,
        total_credits: 12,
        total_hrs_week: 12,
      },
      {
        semester: "Total of 7&8",
        DSC: "Major A:8 or 11 Project in A1",
        nature: "",
        total_courses: "8 or 11",
        total_credits: 44,
        total_hrs_week: 44,
      },
      {
        semester: "Grand Total",
        DSC: "Major A1:18 or 20 courses of 4-credits each + 6 courses of 3-credit each + internship of 2-credit = 92 or 100 credits",
        nature: "",
        total_courses: "44 or 47",
        total_credits: 177,
        total_hrs_week: 186,
      },
    ],
  },

  // Humanities

  {
    pathway: "Single Major",
    discipline: "Humanities",
    courses: [
      {
        semester: 1,
        DSC: "A,B,C",
        AEC: "1(E)(With P)",
        SEC: "",
        MDC: "1",
        VAC: "1(OL)",
        total_courses: 6,
        total_credits: 21,
        total_hrs_week: 22,
      },
      {
        semester: 2,
        DSC: "A,B,C",
        AEC: "1(OL)(With P)",
        SEC: "",
        MDC: "1",
        VAC: "1(E)",
        total_courses: 6,
        total_credits: 21,
        total_hrs_week: 22,
      },
      {
        semester: 3,
        DSC: "A,A,A,B",
        AEC: "1(E)(With P)",
        SEC: "",
        MDC: "1(E&OL)(With KS)",
        VAC: "",
        total_courses: 6,
        total_credits: 22,
        total_hrs_week: 23,
      },
      {
        semester: 4,
        DSC: "A,A,A,C",
        AEC: "1(OL)",
        SEC: "1(E)",
        MDC: "",
        VAC: "",
        total_courses: 6,
        total_credits: 22,
        total_hrs_week: 22,
      },
      {
        semester: 5,
        DSC: "A,A,A,A,A*(*Elective 1)",
        AEC: "",
        SEC: "1",
        MDC: "",
        VAC: "",
        total_courses: 6,
        total_credits: 23,
        total_hrs_week: 23,
      },
      {
        semester: 6,
        DSC: "A,A,A,A*(*Elective 2)",
        AEC: "",
        SEC: "1",
        MDC: "",
        VAC: "1(E)",
        total_courses: 6,
        total_credits: 22,
        total_hrs_week: 22,
      },
      {
        semester: "Total",
        DSC: "Major A:17 MinorB:3 MinorC:3",
        AEC: "4",
        SEC: "3",
        MDC: "3",
        VAC: "3",
        total_courses: 36,
        total_credits: "131+2(Internship)=133",
        total_hrs_week: 134,
      },
    ],
    courses_after_six_sem: [
      {
        semester: 7,
        DSC: "Major A, A ,A ,A ,A ,A",
        nature: "Six courses of first-year-PG level.",
        total_courses: 6,
        total_credits: 24,
        total_hrs_week: 24,
      },
      {
        semester: "8(1)",
        nature:
          "• Two courses of first-year-PG level • They should be taught in the blended mode. • The student can choose to do two online courses from repositories approved by the Board of Study. • Instead of two Major courses, the student can choose to do two Minor courses in any discipline. In this case, the two courses are of third-year-UG level (level 300 & above)  • Instead of Project, three courses of first-year PG level in the Major discipline can be chosen.  ",
        DSC: "Major A, A or Minor in any discipline B, B",
        total_courses: 2,
        total_credits: 8,
        total_hrs_week: 8,
      },
      {
        semester: "8(2)",
        nature:
          " Instead of Project, three courses of first-year PG level in the Major discipline can be chosen.  ",
        DSC: "Project in A (credit 12) or Major A, A, A ",
        total_courses: 3,
        total_credits: 12,
        total_hrs_week: 12,
      },
      {
        semester: "Total of 7&8",
        DSC: "Major A:8 or 11 Project in A",
        nature: "",
        total_courses: "8 or 11",
        total_credits: 44,
        total_hrs_week: 44,
      },
      {
        semester: "Grand Total",
        DSC: "Major A:25 or 28 Minor(s):6 or 8 Project in A",
        nature: "",
        total_courses: "44 or 47",
        total_credits: 177,
        total_hrs_week: 178,
      },
    ],
  },
  {
    pathway: " Major with multiple Disciplines ",
    discipline: "Humanities",
    courses: [
      {
        semester: 1,
        DSC: "A,B,C",
        AEC: "1(E)(With P)",
        SEC: "",
        MDC: "1",
        VAC: "1(OL)",
        total_courses: 6,
        total_credits: 21,
        total_hrs_week: 22,
      },
      {
        semester: 2,
        DSC: "A,B,C",
        AEC: "1(OL)(With P)",
        SEC: "",
        MDC: "1",
        VAC: "1(E)",
        total_courses: 6,
        total_credits: 21,
        total_hrs_week: 22,
      },
      {
        semester: 3,
        DSC: "A,A,A,B",
        AEC: "1(E)(With P)",
        SEC: "",
        MDC: "1(E&OL)(With KS)",
        VAC: "",
        total_courses: 6,
        total_credits: 22,
        total_hrs_week: 23,
      },
      {
        semester: 4,
        DSC: "A,A,A,C",
        AEC: "1(OL)",
        SEC: "1(E)",
        MDC: "",
        VAC: "",
        total_courses: 6,
        total_credits: 22,
        total_hrs_week: 22,
      },
      {
        semester: 5,
        DSC: "A,A,A,A,A*(Elective 1)",
        AEC: "",
        SEC: "1",
        MDC: "",
        VAC: "",
        total_courses: 6,
        total_credits: 23,
        total_hrs_week: 23,
      },
      {
        semester: 6,
        DSC: "A,A,A,A*(*Elective 2)",
        AEC: "",
        SEC: "1",
        MDC: "",
        VAC: "1(E)",
        total_courses: 6,
        total_credits: 22,
        total_hrs_week: 22,
      },
      {
        semester: "Total",
        DSC: "Major A:17 MinorB:3 MajorC:3",
        AEC: "4",
        SEC: "3",
        MDC: "3",
        VAC: "3",
        total_courses: 36,
        total_credits: "131+2(Internship)=133",
        total_hrs_week: 134,
      },
    ],
    courses_after_six_sem: [
      {
        semester: 7,
        DSC: "Major A, A ,A ,A ,A ,A",
        nature: "Six courses of first-year-PG level.",
        total_courses: 6,
        total_credits: 24,
        total_hrs_week: 24,
      },
      {
        semester: "8(1)",
        nature:
          "• Two courses of first-year-PG level • They should be taught in the blended mode. • The student can choose to do two online courses from repositories approved by the Board of Study. • Instead of two Major courses, the student can choose to do two Minor courses in any discipline. In this case, the two courses are of third-year-UG level (level 300 & above)  • Instead of Project, three courses of first-year PG level in the Major discipline can be chosen.  ",
        DSC: "Major A, A or Minor in any discipline B, B  /  Project in A (credit 12) or Major A, A, A ",
        total_courses: 2,
        total_credits: 8,
        total_hrs_week: 8,
      },
      {
        semester: "8(2)",
        nature:
          " Instead of Project, three courses of first-year PG level in the Major discipline can be chosen.  ",
        DSC: "Project in A (credit 12) or Major A, A, A ",
        total_courses: 3,
        total_credits: 12,
        total_hrs_week: 12,
      },
      {
        semester: "Total of 7&8",
        DSC: "Major A:8 or 11 Project in A",
        nature: "",
        total_courses: "8 or 11",
        total_credits: 44,
        total_hrs_week: 44,
      },
      {
        semester: "Grand Total",
        DSC: "Major A:25 or 28 Minor(s):6 or 8 Project in A",
        nature: "",
        total_courses: "44 or 47",
        total_credits: 177,
        total_hrs_week: 178,
      },
    ],
  },
  {
    pathway: "Major with Minor",
    discipline: "Humanities",
    courses: [
      {
        semester: 1,
        DSC: "A,B,B",
        AEC: "1(E)(With P)",
        SEC: "",
        MDC: "1",
        VAC: "1(OL)",
        total_courses: 6,
        total_credits: 21,
        total_hrs_week: 22,
      },
      {
        semester: 2,
        DSC: "A,B,B",
        AEC: "1(OL)(With P)",
        SEC: "",
        MDC: "1",
        VAC: "1(E)",
        total_courses: 6,
        total_credits: 21,
        total_hrs_week: 22,
      },
      {
        semester: 3,
        DSC: "A,A,A,B",
        AEC: "1(E)(With P)",
        SEC: "",
        MDC: "1(E&OL)(With KS)",
        VAC: "",
        total_courses: 6,
        total_credits: 22,
        total_hrs_week: 23,
      },
      {
        semester: 4,
        DSC: "A,A,A,B",
        AEC: "1(OL)",
        SEC: "1(E)",
        MDC: "",
        VAC: "",
        total_courses: 6,
        total_credits: 22,
        total_hrs_week: 23,
      },
      {
        semester: 5,
        DSC: "A,A,A,A,A*(*Elective 1)",
        AEC: "",
        SEC: "1",
        MDC: "",
        VAC: "",
        total_courses: 6,
        total_credits: 23,
        total_hrs_week: 23,
      },
      {
        semester: 6,
        DSC: "A,A,A,A*(*Elective 2)",
        AEC: "",
        SEC: "1",
        MDC: "",
        VAC: "1(E)",
        total_courses: 6,
        total_credits: 22,
        total_hrs_week: 22,
      },

      {
        semester: "Total",
        DSC: "Major A:17 MinorB:6",
        AEC: "4",
        SEC: "3",
        MDC: "3",
        VAC: "3",
        total_courses: 36,
        total_credits: "131+2(Internship)=133",
        total_hrs_week: 134,
      },
    ],
    courses_after_six_sem: [
      {
        semester: 7,
        DSC: "Major A, A ,A ,A ,A ,A",
        nature: "Six courses of first-year-PG level.",
        total_courses: 6,
        total_credits: 24,
        total_hrs_week: 24,
      },
      {
        semester: "8(1)",
        nature:
          "• Two courses of first-year-PG level • They should be taught in the blended mode. • The student can choose to do two online courses from repositories approved by the Board of Study. • Instead of two Major courses, the student can choose to do two Minor courses in any discipline. In this case, the two courses are of third-year-UG level (level 300 & above)  • Instead of Project, three courses of first-year PG level in the Major discipline can be chosen.  ",
        DSC: "Major A, A or Minor in any discipline B, B",
        total_courses: 2,
        total_credits: 8,
        total_hrs_week: 8,
      },
      {
        semester: "8(2)",
        nature:
          " Instead of Project, three courses of first-year PG level in the Major discipline can be chosen.  ",
        DSC: "Project in A (credit 12) or Major A, A, A ",
        total_courses: 3,
        total_credits: 12,
        total_hrs_week: 12,
      },
      {
        semester: "Total of 7&8",
        DSC: "Major A:8 or 11 Project in A",
        nature: "",
        total_courses: "8 or 11",
        total_credits: 44,
        total_hrs_week: 44,
      },
      {
        semester: "Grand Total",
        DSC: "Major A:25 or 28 Minor(s):6 or 8 Project in A",
        nature: "",
        total_courses: "44 or 47",
        total_credits: 177,
        total_hrs_week: 178,
      },
    ],
  },

  {
    pathway: "Major with Vocational Minor",
    discipline: "Humanities",
    courses: [
      {
        semester: 1,
        DSC: "A,B(P),B(P)",
        AEC: "1(E)(With P)",
        SEC: "",
        MDC: "1",
        VAC: "1(OL)",
        total_courses: 6,
        total_credits: 21,
        total_hrs_week: 24,
      },
      {
        semester: 2,
        DSC: "A,B(P),B(P)",
        AEC: "1(OL)(With P)",
        SEC: "",
        MDC: "1",
        VAC: "1(E)",
        total_courses: 6,
        total_credits: 21,
        total_hrs_week: 24,
      },
      {
        semester: 3,
        DSC: "A,A,A(P),B",
        AEC: "1(E)(With P)",
        SEC: "",
        MDC: "1(E&OL)(With KS)",
        VAC: "",
        total_courses: 6,
        total_credits: 22,
        total_hrs_week: 24,
      },
      {
        semester: 4,
        DSC: "A,A,A(P),B",
        AEC: "1(OL)",
        SEC: "1(E)",
        MDC: "",
        VAC: "",
        total_courses: 6,
        total_credits: 22,
        total_hrs_week: 23,
      },
      {
        semester: 5,
        DSC: "A,A,A,A(P),A*(*Elective 1)",
        AEC: "",
        SEC: "1",
        MDC: "",
        VAC: "",
        total_courses: 6,
        total_credits: 23,
        total_hrs_week: 24,
      },
      {
        semester: 6,
        DSC: "A,A,A(P),A*(*Elective 2)",
        AEC: "",
        SEC: "1",
        MDC: "",
        VAC: "1(E)",
        total_courses: 6,
        total_credits: 22,
        total_hrs_week: 23,
      },
      {
        semester: "Total",
        DSC: "Major A:17 MinorB:6",
        AEC: "4",
        SEC: "3",
        MDC: "3",
        VAC: "3",
        total_courses: 36,
        total_credits: "131+2(Internship)=133",
        total_hrs_week: 142,
      },
    ],
    courses_after_six_sem: [
      {
        semester: 7,
        DSC: "Major A, A ,A ,A ,A ,A",
        nature: "Six courses of first-year-PG level.",
        total_courses: 6,
        total_credits: 24,
        total_hrs_week: 24,
      },
      {
        semester: "8(1)",
        nature:
          "• Two courses of first-year-PG level • They should be taught in the blended mode. • The student can choose to do two online courses from repositories approved by the Board of Study. • Instead of two Major courses, the student can choose to do two Minor courses in any discipline. In this case, the two courses are of third-year-UG level (level 300 & above)  • Instead of Project, three courses of first-year PG level in the Major discipline can be chosen.  ",
        DSC: "Major A, A or Minor in any discipline B, B  /  Project in A (credit 12) or Major A, A, A ",
        total_courses: 2,
        total_credits: 8,
        total_hrs_week: 8,
      },
      {
        semester: "8(2)",
        nature:
          " Instead of Project, three courses of first-year PG level in the Major discipline can be chosen.  ",
        DSC: "Project in A (credit 12) or Major A, A, A ",
        total_courses: 3,
        total_credits: 12,
        total_hrs_week: 12,
      },
      {
        semester: "Total of 7&8",
        DSC: "Major A:8 or 11 Project in A",
        nature: "",
        total_courses: "8 or 11",
        total_credits: 44,
        total_hrs_week: 44,
      },
      {
        semester: "Grand Total",
        DSC: "Major A:25 or 28 Minor(s):6 or 8 Project in A",
        nature: "",
        total_courses: "44 or 47",
        total_credits: 177,
        total_hrs_week: 186,
      },
    ],
  },

  {
    pathway: "Double Major",
    discipline: "Humanities",
    courses: [
      {
        semester: 1,
        DSC: "A,A,B",
        AEC: "1(E)(With P)",
        SEC: "",
        MDC: "1",
        VAC: "1(OL)",
        total_courses: 6,
        total_credits: 21,
        total_hrs_week: 22,
      },
      {
        semester: 2,
        DSC: "A,B,B",
        AEC: "1(OL)(With P)",
        SEC: "",
        MDC: "1",
        VAC: "1(E)",
        total_courses: 6,
        total_credits: 21,
        total_hrs_week: 22,
      },
      {
        semester: 3,
        DSC: "A,A,A,B",
        AEC: "1(E)(With P)",
        SEC: "",
        MDC: "1(E & OL)(WITH KS)",
        VAC: "",
        total_courses: 6,
        total_credits: 22,
        total_hrs_week: 23,
      },
      {
        semester: 4,
        DSC: "A,A,A,B",
        AEC: "1(OL)",
        SEC: "1(E)",
        MDC: "",
        VAC: "",
        total_courses: 6,
        total_credits: 22,
        total_hrs_week: 23,
      },
      {
        semester: 5,
        DSC: "A,A,A,A,A*(*Elective 1)",
        AEC: "",
        SEC: "1",
        MDC: "",
        VAC: "",
        total_courses: 6,
        total_credits: 23,
        total_hrs_week: 23,
      },
      {
        semester: 6,
        DSC: "A,A,A,A*(*Elective 2)",
        AEC: "",
        SEC: "1",
        MDC: "",
        VAC: "1(E)",
        total_courses: 6,
        total_credits: 22,
        total_hrs_week: 22,
      },
      {
        semester: "Total",
        DSC: "Major A:17 Minor B:6",
        AEC: "4",
        SEC: "3",
        MDC: "3",
        VAC: "3",
        total_courses: 36,
        total_credits: "131+2(Internship in A1)=133",
        total_hrs_week: 134,
      },
    ],
    courses_after_six_sem: [
      {
        semester: 7,
        DSC: "Major A, A ,A ,A ,A ,A",
        nature: "Six courses of first-year-PG level.",
        total_courses: 6,
        total_credits: 24,
        total_hrs_week: 24,
      },
      {
        semester: "8(1)",
        nature:
          "• Two courses of first-year-PG level • They should be taught in the blended mode. • The student can choose to do two online courses from repositories approved by the Board of Study. • Instead of two Major courses, the student can choose to do two Minor courses in any discipline. In this case, the two courses are of third-year-UG level (level 300 & above)  • Instead of Project, three courses of first-year PG level in the Major discipline can be chosen.  ",
        DSC: "Major A, A or Minor in any discipline B, B",
        total_courses: 2,
        total_credits: 8,
        total_hrs_week: 8,
      },
      {
        semester: "8(2)",
        nature:
          " Instead of Project, three courses of first-year PG level in the Major discipline can be chosen.  ",
        DSC: "Project in A (credit 12) or Major A, A, A ",
        total_courses: 3,
        total_credits: 12,
        total_hrs_week: 12,
      },
      {
        semester: "Total of 7&8",
        DSC: "Major A:8 or 11 Project in A",
        nature: "",
        total_courses: "8 or 11",
        total_credits: 44,
        total_hrs_week: 44,
      },
      {
        semester: "Grand Total",
        DSC: "Major A:25 or 28 Minors:6 or 8 Project in A",
        nature: "",
        total_courses: "44 or 47",
        total_credits: 177,
        total_hrs_week: 178,
      },
    ],
  },

  // Languages
  {
    pathway: "Single Major",
    discipline: "Languages",
    courses: [
      {
        semester: 1,
        DSC: "A,B,C",
        AEC: "1(E)(With P)",
        SEC: "",
        MDC: "1",
        VAC: "1(OL)",
        total_courses: 6,
        total_credits: 21,
        total_hrs_week: 22,
      },
      {
        semester: 2,
        DSC: "A,B,C",
        AEC: "1(OL)(With P)",
        SEC: "",
        MDC: "1",
        VAC: "1(E)",
        total_courses: 6,
        total_credits: 21,
        total_hrs_week: 22,
      },
      {
        semester: 3,
        DSC: "A,A,A,B",
        AEC: "1(E)(With P)",
        SEC: "",
        MDC: "1(E&OL)(With KS)",
        VAC: "",
        total_courses: 6,
        total_credits: 22,
        total_hrs_week: 23,
      },
      {
        semester: 4,
        DSC: "A,A,A,C",
        AEC: "1(OL)",
        SEC: "1(E)",
        MDC: "",
        VAC: "",
        total_courses: 6,
        total_credits: 22,
        total_hrs_week: 22,
      },
      {
        semester: 5,
        DSC: "A,A,A,A,A*(*Elective 1)",
        AEC: "",
        SEC: "1",
        MDC: "",
        VAC: "",
        total_courses: 6,
        total_credits: 23,
        total_hrs_week: 23,
      },
      {
        semester: 6,
        DSC: "A,A,A,A*(*Elective 2)",
        AEC: "",
        SEC: "1",
        MDC: "",
        VAC: "1(E)",
        total_courses: 6,
        total_credits: 22,
        total_hrs_week: 22,
      },
      {
        semester: "Total",
        DSC: "Major A:17 MinorB:3 MinorC:3",
        AEC: "4",
        SEC: "3",
        MDC: "3",
        VAC: "3",
        total_courses: 36,
        total_credits: "131+2(Internship)=133",
        total_hrs_week: 134,
      },
    ],
    courses_after_six_sem: [
      {
        semester: 7,
        DSC: "Major A, A ,A ,A ,A ,A",
        nature: "Six courses of first-year-PG level.",
        total_courses: 6,
        total_credits: 24,
        total_hrs_week: 24,
      },
      {
        semester: "8(1)",
        nature:
          "• Two courses of first-year-PG level • They should be taught in the blended mode. • The student can choose to do two online courses from repositories approved by the Board of Study. • Instead of two Major courses, the student can choose to do two Minor courses in any discipline. In this case, the two courses are of third-year-UG level (level 300 & above)  • Instead of Project, three courses of first-year PG level in the Major discipline can be chosen.  ",
        DSC: "Major A, A or Minor in any discipline B, B",
        total_courses: 2,
        total_credits: 8,
        total_hrs_week: 8,
      },
      {
        semester: "8(2)",
        nature:
          " Instead of Project, three courses of first-year PG level in the Major discipline can be chosen.  ",
        DSC: "Project in A (credit 12) or Major A, A, A ",
        total_courses: 3,
        total_credits: 12,
        total_hrs_week: 12,
      },
      {
        semester: "Total of 7&8",
        DSC: "Major A:8 or 11 Project in A",
        nature: "",
        total_courses: "8 or 11",
        total_credits: 44,
        total_hrs_week: 44,
      },
      {
        semester: "Grand Total",
        DSC: "Major A:25 or 28 Minor(s):6 or 8 Project in A",
        nature: "",
        total_courses: "44 or 47",
        total_credits: 177,
        total_hrs_week: 178,
      },
    ],
  },
  {
    pathway: " Major with multiple Disciplines ",
    discipline: "Languages",
    courses: [
      {
        semester: 1,
        DSC: "A,B,C",
        AEC: "1(E)(With P)",
        SEC: "",
        MDC: "1",
        VAC: "1(OL)",
        total_courses: 6,
        total_credits: 21,
        total_hrs_week: 22,
      },
      {
        semester: 2,
        DSC: "A,B,C",
        AEC: "1(OL)(With P)",
        SEC: "",
        MDC: "1",
        VAC: "1(E)",
        total_courses: 6,
        total_credits: 21,
        total_hrs_week: 22,
      },
      {
        semester: 3,
        DSC: "A,A,A,B",
        AEC: "1(E)(With P)",
        SEC: "",
        MDC: "1(E&OL)(With KS)",
        VAC: "",
        total_courses: 6,
        total_credits: 22,
        total_hrs_week: 23,
      },
      {
        semester: 4,
        DSC: "A,A,A,C",
        AEC: "1(OL)",
        SEC: "1(E)",
        MDC: "",
        VAC: "",
        total_courses: 6,
        total_credits: 22,
        total_hrs_week: 22,
      },
      {
        semester: 5,
        DSC: "A,A,A,A,A*(Elective 1)",
        AEC: "",
        SEC: "1",
        MDC: "",
        VAC: "",
        total_courses: 6,
        total_credits: 23,
        total_hrs_week: 23,
      },
      {
        semester: 6,
        DSC: "A,A,A,A*(*Elective 2)",
        AEC: "",
        SEC: "1",
        MDC: "",
        VAC: "1(E)",
        total_courses: 6,
        total_credits: 22,
        total_hrs_week: 22,
      },
      {
        semester: "Total",
        DSC: "Major A:17 MinorB:3 MajorC:3",
        AEC: "4",
        SEC: "3",
        MDC: "3",
        VAC: "3",
        total_courses: 36,
        total_credits: "131+2(Internship)=133",
        total_hrs_week: 134,
      },
    ],
    courses_after_six_sem: [
      {
        semester: 7,
        DSC: "Major A, A ,A ,A ,A ,A",
        nature: "Six courses of first-year-PG level.",
        total_courses: 6,
        total_credits: 24,
        total_hrs_week: 24,
      },
      {
        semester: "8(1)",
        nature:
          "• Two courses of first-year-PG level • They should be taught in the blended mode. • The student can choose to do two online courses from repositories approved by the Board of Study. • Instead of two Major courses, the student can choose to do two Minor courses in any discipline. In this case, the two courses are of third-year-UG level (level 300 & above)  • Instead of Project, three courses of first-year PG level in the Major discipline can be chosen.  ",
        DSC: "Major A, A or Minor in any discipline B, B  /  Project in A (credit 12) or Major A, A, A ",
        total_courses: 2,
        total_credits: 8,
        total_hrs_week: 8,
      },
      {
        semester: "8(2)",
        nature:
          " Instead of Project, three courses of first-year PG level in the Major discipline can be chosen.  ",
        DSC: "Project in A (credit 12) or Major A, A, A ",
        total_courses: 3,
        total_credits: 12,
        total_hrs_week: 12,
      },
      {
        semester: "Total of 7&8",
        DSC: "Major A:8 or 11 Project in A",
        nature: "",
        total_courses: "8 or 11",
        total_credits: 44,
        total_hrs_week: 44,
      },
      {
        semester: "Grand Total",
        DSC: "Major A:25 or 28 Minor(s):6 or 8 Project in A",
        nature: "",
        total_courses: "44 or 47",
        total_credits: 177,
        total_hrs_week: 178,
      },
    ],
  },
  {
    pathway: "Major with Minor",
    discipline: "Languages",
    courses: [
      {
        semester: 1,
        DSC: "A,B,B",
        AEC: "1(E)(With P)",
        SEC: "",
        MDC: "1",
        VAC: "1(OL)",
        total_courses: 6,
        total_credits: 21,
        total_hrs_week: 22,
      },
      {
        semester: 2,
        DSC: "A,B,B",
        AEC: "1(OL)(With P)",
        SEC: "",
        MDC: "1",
        VAC: "1(E)",
        total_courses: 6,
        total_credits: 21,
        total_hrs_week: 22,
      },
      {
        semester: 3,
        DSC: "A,A,A,B",
        AEC: "1(E)(With P)",
        SEC: "",
        MDC: "1(E&OL)(With KS)",
        VAC: "",
        total_courses: 6,
        total_credits: 22,
        total_hrs_week: 23,
      },
      {
        semester: 4,
        DSC: "A,A,A,B",
        AEC: "1(OL)",
        SEC: "1(E)",
        MDC: "",
        VAC: "",
        total_courses: 6,
        total_credits: 22,
        total_hrs_week: 23,
      },
      {
        semester: 5,
        DSC: "A,A,A,A,A*(*Elective 1)",
        AEC: "",
        SEC: "1",
        MDC: "",
        VAC: "",
        total_courses: 6,
        total_credits: 23,
        total_hrs_week: 23,
      },
      {
        semester: 6,
        DSC: "A,A,A,A*(*Elective 2)",
        AEC: "",
        SEC: "1",
        MDC: "",
        VAC: "1(E)",
        total_courses: 6,
        total_credits: 22,
        total_hrs_week: 22,
      },
      {
        semester: "Total",
        DSC: "Major A:17 MinorB:6",
        AEC: "4",
        SEC: "3",
        MDC: "3",
        VAC: "3",
        total_courses: 36,
        total_credits: "131+2(Internship)=133",
        total_hrs_week: 134,
      },
    ],
    courses_after_six_sem: [
      {
        semester: 7,
        DSC: "Major A, A ,A ,A ,A ,A",
        nature: "Six courses of first-year-PG level.",
        total_courses: 6,
        total_credits: 24,
        total_hrs_week: 24,
      },
      {
        semester: "8(1)",
        nature:
          "• Two courses of first-year-PG level • They should be taught in the blended mode. • The student can choose to do two online courses from repositories approved by the Board of Study. • Instead of two Major courses, the student can choose to do two Minor courses in any discipline. In this case, the two courses are of third-year-UG level (level 300 & above)  • Instead of Project, three courses of first-year PG level in the Major discipline can be chosen.  ",
        DSC: "Major A, A or Minor in any discipline B, B",
        total_courses: 2,
        total_credits: 8,
        total_hrs_week: 8,
      },
      {
        semester: "8(2)",
        nature:
          " Instead of Project, three courses of first-year PG level in the Major discipline can be chosen.  ",
        DSC: "Project in A (credit 12) or Major A, A, A ",
        total_courses: 3,
        total_credits: 12,
        total_hrs_week: 12,
      },
      {
        semester: "Total of 7&8",
        DSC: "Major A:8 or 11 Project in A",
        nature: "",
        total_courses: "8 or 11",
        total_credits: 44,
        total_hrs_week: 44,
      },
      {
        semester: "Grand Total",
        DSC: "Major A:25 or 28 Minor(s):6 or 8 Project in A",
        nature: "",
        total_courses: "44 or 47",
        total_credits: 177,
        total_hrs_week: 178,
      },
    ],
  },

  {
    pathway: "Major with Vocational Minor",
    discipline: "Languages",
    courses: [
      {
        semester: 1,
        DSC: "A,B(P),B(P)",
        AEC: "1(E)(With P)",
        SEC: "",
        MDC: "1",
        VAC: "1(OL)",
        total_courses: 6,
        total_credits: 21,
        total_hrs_week: 24,
      },
      {
        semester: 2,
        DSC: "A,B(P),B(P)",
        AEC: "1(OL)(With P)",
        SEC: "",
        MDC: "1",
        VAC: "1(E)",
        total_courses: 6,
        total_credits: 21,
        total_hrs_week: 24,
      },
      {
        semester: 3,
        DSC: "A,A,A(P),B",
        AEC: "1(E)(With P)",
        SEC: "",
        MDC: "1(E&OL)(With KS)",
        VAC: "",
        total_courses: 6,
        total_credits: 22,
        total_hrs_week: 24,
      },
      {
        semester: 4,
        DSC: "A,A,A(P),B",
        AEC: "1(OL)",
        SEC: "1(E)",
        MDC: "",
        VAC: "",
        total_courses: 6,
        total_credits: 22,
        total_hrs_week: 23,
      },
      {
        semester: 5,
        DSC: "A,A,A,A(P),A*(*Elective 1)",
        AEC: "",
        SEC: "1",
        MDC: "",
        VAC: "",
        total_courses: 6,
        total_credits: 23,
        total_hrs_week: 24,
      },
      {
        semester: 6,
        DSC: "A,A,A(P),A*(*Elective 2)",
        AEC: "",
        SEC: "1",
        MDC: "",
        VAC: "1(E)",
        total_courses: 6,
        total_credits: 22,
        total_hrs_week: 23,
      },
      {
        semester: "Total",
        DSC: "Major A:17 MinorB:6",
        AEC: "4",
        SEC: "3",
        MDC: "3",
        VAC: "3",
        total_courses: 36,
        total_credits: "131+2(Internship)=133",
        total_hrs_week: 142,
      },
    ],
    courses_after_six_sem: [
      {
        semester: 7,
        DSC: "Major A, A ,A ,A ,A ,A",
        nature: "Six courses of first-year-PG level.",
        total_courses: 6,
        total_credits: 24,
        total_hrs_week: 24,
      },
      {
        semester: "8(1)",
        nature:
          "• Two courses of first-year-PG level • They should be taught in the blended mode. • The student can choose to do two online courses from repositories approved by the Board of Study. • Instead of two Major courses, the student can choose to do two Minor courses in any discipline. In this case, the two courses are of third-year-UG level (level 300 & above)  • Instead of Project, three courses of first-year PG level in the Major discipline can be chosen.  ",
        DSC: "Major A, A or Minor in any discipline B, B  /  Project in A (credit 12) or Major A, A, A ",
        total_courses: 2,
        total_credits: 8,
        total_hrs_week: 8,
      },
      {
        semester: "8(2)",
        nature:
          " Instead of Project, three courses of first-year PG level in the Major discipline can be chosen.  ",
        DSC: "Project in A (credit 12) or Major A, A, A ",
        total_courses: 3,
        total_credits: 12,
        total_hrs_week: 12,
      },
      {
        semester: "Total of 7&8",
        DSC: "Major A:8 or 11 Project in A",
        nature: "",
        total_courses: "8 or 11",
        total_credits: 44,
        total_hrs_week: 44,
      },
      {
        semester: "Grand Total",
        DSC: "Major A:25 or 28 Minor(s):6 or 8 Project in A",
        nature: "",
        total_courses: "44 or 47",
        total_credits: 177,
        total_hrs_week: 186,
      },
    ],
  },

  {
    pathway: "Double Major",
    discipline: "Languages",
    courses: [
      {
        semester: 1,
        DSC: "A,A,B",
        AEC: "1(E)(With P)",
        SEC: "",
        MDC: "1",
        VAC: "1(OL)",
        total_courses: 6,
        total_credits: 21,
        total_hrs_week: 22,
      },
      {
        semester: 2,
        DSC: "A,B,B",
        AEC: "1(OL)(With P)",
        SEC: "",
        MDC: "1",
        VAC: "1(E)",
        total_courses: 6,
        total_credits: 21,
        total_hrs_week: 22,
      },
      {
        semester: 3,
        DSC: "A,A,A,B",
        AEC: "1(E)(With P)",
        SEC: "",
        MDC: "1(E & OL)(WITH KS)",
        VAC: "",
        total_courses: 6,
        total_credits: 22,
        total_hrs_week: 23,
      },
      {
        semester: 4,
        DSC: "A,A,A,B",
        AEC: "1(OL)",
        SEC: "1(E)",
        MDC: "",
        VAC: "",
        total_courses: 6,
        total_credits: 22,
        total_hrs_week: 23,
      },
      {
        semester: 5,
        DSC: "A,A,A,A,A*(*Elective 1)",
        AEC: "",
        SEC: "1",
        MDC: "",
        VAC: "",
        total_courses: 6,
        total_credits: 23,
        total_hrs_week: 23,
      },
      {
        semester: 6,
        DSC: "A,A,A,A*(*Elective 2)",
        AEC: "",
        SEC: "1",
        MDC: "",
        VAC: "1(E)",
        total_courses: 6,
        total_credits: 22,
        total_hrs_week: 22,
      },
      {
        semester: "Total",
        DSC: "Major A:17 Minor B:6",
        AEC: "4",
        SEC: "3",
        MDC: "3",
        VAC: "3",
        total_courses: 36,
        total_credits: "131+2(Internship in A1)=133",
        total_hrs_week: 134,
      },
    ],
    courses_after_six_sem: [
      {
        semester: 7,
        DSC: "Major A, A ,A ,A ,A ,A",
        nature: "Six courses of first-year-PG level.",
        total_courses: 6,
        total_credits: 24,
        total_hrs_week: 24,
      },
      {
        semester: "8(1)",
        nature:
          "• Two courses of first-year-PG level • They should be taught in the blended mode. • The student can choose to do two online courses from repositories approved by the Board of Study. • Instead of two Major courses, the student can choose to do two Minor courses in any discipline. In this case, the two courses are of third-year-UG level (level 300 & above)  • Instead of Project, three courses of first-year PG level in the Major discipline can be chosen.  ",
        DSC: "Major A, A or Minor in any discipline B, B",
        total_courses: 2,
        total_credits: 8,
        total_hrs_week: 8,
      },
      {
        semester: "8(2)",
        nature:
          " Instead of Project, three courses of first-year PG level in the Major discipline can be chosen.  ",
        DSC: "Project in A (credit 12) or Major A, A, A ",
        total_courses: 3,
        total_credits: 12,
        total_hrs_week: 12,
      },
      {
        semester: "Total of 7&8",
        DSC: "Major A:8 or 11 Project in A",
        nature: "",
        total_courses: "8 or 11",
        total_credits: 44,
        total_hrs_week: 44,
      },
      {
        semester: "Grand Total",
        DSC: "Major A:25 or 28 Minors:6 or 8 Project in A",
        nature: "",
        total_courses: "44 or 47",
        total_credits: 177,
        total_hrs_week: 178,
      },
    ],
  },
];
