export const Courses: any[] = [
  {
    pathway: "Single Major Pathway",
    discipline: "Science",
    courses: [
      {
        semester: 1,
        DSC: "A(P),B(P),C(P)",
        AEC: "1(E)(With P)",
        SEC: "",
        MDC: "1",
        VAC: "1(OL)",
        total_courses: 6,
        total_credits: 21,
        total_hrs_week: 25,
      },
      {
        semester: 2,
        DSC: "A(P),B(P),C(P)",
        AEC: "1(OL)(With P)",
        SEC: "",
        MDC: "1",
        VAC: "1(E)",
        total_courses: 6,
        total_credits: 21,
        total_hrs_week: 25,
      },
      {
        semester: 3,
        DSC: "A,A,A(P),B(P)",
        AEC: "1(E)(With P)",
        SEC: "",
        MDC: "1(E&OL)(With KS)",
        VAC: "",
        total_courses: 6,
        total_credits: 21,
        total_hrs_week: 25,
      },
      {
        semester: 4,
        DSC: "A,A,A(P),C(P)",
        AEC: "1(OL)",
        SEC: "1(E)",
        MDC: "",
        VAC: "",
        total_courses: 6,
        total_credits: 22,
        total_hrs_week: 24,
      },
      {
        semester: 5,
        DSC: "A,A,A(P),A(P),A*",
        AEC: "",
        SEC: "1",
        MDC: "",
        VAC: "",
        total_courses: 6,
        total_credits: 23,
        total_hrs_week: 25,
      },
      {
        semester: 6,
        DSC: "A,A(P),A(P),A*",
        AEC: "",
        SEC: "1",
        MDC: "",
        VAC: "1(E)",
        total_courses: 6,
        total_credits: 22,
        total_hrs_week: 24,
      },
      {
        semester: "Total",
        DSC: "Major A:17 Minor(B+C):6",
        AEC: "4",
        SEC: "3",
        MDC: "3",
        VAC: "3",
        total_courses: 36,
        total_credits: "131+2(Internship)=133",
        total_hrs_week: 148,
      },
    ],
    courses_after_six_sem: [
      {
        semester: 7,
        DSC: "Major A, A ,A ,A ,A(P) ,A(P)",
        nature: "Six courses of first-year-PG level.",
        total_courses: 6,
        total_credits: 24,
        total_hrs_week: 26,
      },
      {
        semester: 8,
        nature:
          "• Two courses of first-year-PG level • They should be taught in the blended mode. • The student can choose to do two online courses from repositories approved by the Board of Study. • Instead of two Major courses, the student can choose to do two Minor courses in any discipline. In this case, the two courses are of third-year-UG level (level 300 & above)  • Instead of Project, three courses of first-year PG level in the Major discipline can be chosen.  ",
        DSC: "Major A, A or Minor in any discipline B, B  /  Project in A (credit 12) or Major A, A, A ",
        total_courses: 2,
        total_credits: 8,
        total_hrs_week: 8,
      },
      {
        semester: "Total of 7&8",
        DSC: "Major A:8 or 11 Project in A",
        nature: "",
        total_courses: "8 or 11",
        total_credits: 44,
        total_hrs_week: 46,
      },
      {
        semester: "Grand Total",
        DSC: "Major A:25 or 28 Minor(s):6 or 8",
        nature: "",
        total_courses: "44 or 47",
        total_credits: 177,
        total_hrs_week: 194,
      },
    ],
  },
];
